time_left_turn: 3.5
time_straight_turn: 2
time_right_turn: 2

ff_left: 0.1
ff_straight: 0
ff_right: -0.1

LFparams_left: {phi_max: -0.5, phi_min: -2, range_est: 0.6, red_to_white: true, use_yellow: false}
LFparams_straight: {"red_to_white": True}
LFparams_right: {phi_max: 2, phi_min: 0.5, range_est: 0.4, red_to_white: false}

omega_min_left: -1.5
omega_max_left: 0.8
omega_min_straight: -1
omega_max_straight: 1
omega_min_right: -3
omega_max_right: 999

debug_dir: -1
